import { Inter } from "next/font/google";
import "./globals.css";

import Nav from "./Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticket Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " flex flex-col"}>
        {/* <Nav /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}

















